export const REPORT_LIST_REQUEST = 'REPORT_LIST_REQUEST'
export const REPORT_LIST_SUCCESS = 'REPORT_LIST_SUCCESS'
export const REPORT_LIST_FAIL = 'REPORT_LIST_FAIL'

export const REPORT_DETAILS_REQUEST = 'REPORT_DETAILS_REQUEST'
export const REPORT_DETAILS_SUCCESS = 'REPORT_DETAILS_SUCCESS'
export const REPORT_DETAILS_FAIL = 'REPORT_DETAILS_FAIL'